
ELK_VERSION=7.13.1

KAFKA_HOST=localhost
DOCKER_KAFKA_HOST=kafka
CLEARING_HOUSE_KAFKA='localhost'
CLEARING_HOUSE_API_VERSION="0.11.5"
KAFKA_PASSWORD=''

BASKERVILLE_IMAGE=equalitie/baskerville:latest
BASKERVILLE_POSTGRES_USER=postgres
BASKERVILLE_POSTGRES_PASSWORD=changeme
BASKERVILLE_POSTGRES_PORT=5432

BASKERVILLE_CLIENT_ID='yourid'

DEFLECT_DNET=dnet1
GF_SECURITY_ADMIN_PASSWORD=Adm1nPa$$

# for the dashboard
JWT_SECRET=sosecret
ADMIN_PASS=pass
SECRET_KEY='a very very secret key preferably through an env variable'

PROJECT_ROOT='/path/to/baskerville_client'

KAFKA_KEYSTORE_PASSWORD="..."
KAFKA_TRUSTSTORE_PASSWORD="..."
