# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: PostgreSQL
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: baskerville
    user: postgres
    secureJsonData:
      password: 'changeme'
    jsonData:
      sslmode: "disable"